name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liJLnM7G84walI14"
GITHUB_OWNER = "xiao429887822"
GITHUB_REPO = "navdemo"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://dh.leti.ltd/api/auth"
NEXT_PUBLIC_API_URL="https://dh.leti.ltd"

